### ISSUE TITLE
모듈로 바뀌면서 DB 사용이 가능해지면서 궁금한점

### ISSUE THREAD

**Issue by wookho** [bjrambo/parserlink#1]
prologos	6시간 전
사실 한번 파싱한 url의 이미지나 정보를 저장했다가 보여주는것에대해 서버 공간 낭비등으로 인해 부정적인 입장이었습니다만 @웹지기님 말씀듣고나니 수긍이 가네요.
이 부분의 기능 구현은 그렇게 어렵지 않을것으로 보입니다만 람보님이 모듈로 포팅 하신다니 애드온에 도움을 드리기보다는 조금 기다려 보겠습니다.

xe타운에서 언급된 내용입니다. 서버에서 매번 파싱을 하지 않도록 하기 위해 파싱해온 정보를 저장하거나 또 이미지를 따로 서버에 저장해서 매번 파싱을 하지 않아도 되도록 하기 위한 게획이 있으신지 궁금합니다.

**Comment by bjrambo** [comment]
캐시데이터로 기록해둬서 해당 캐시에 대이터가 있으면 저장해두는것도 나쁘지 않겠어요

**Comment by wookho** [comment]
저희가 최대한 파싱대상에게 피해를 주지 않는 것으로 노력해 줄때 많은 보다 많은 사이트들이 파싱에 대한 부정적인 생각으로 파싱 자체를 차단하는 일이 줄어들 것으로 생각되요!!!!!!

**Comment by bjrambo** [comment]
디비에 링크에 대한 데이터들을 시리얼라이즈 데이터로 저장한다음 해당 저장된 데이터들을 가지고 불러오도록 하고 XE object캐시 사용자들을 위한 디비쿼리를 최대한 줄일방법도 간구.

**Comment by bjrambo** [comment]
module_srl
document_srl
url_srl
site_url - index
site_data - big text

하다가 추가..

**Comment by bjrambo** [comment]
```xml
<table name="parserlink_url_data">
	<column name="module_srl" type="number" size="11" notnull="notnull" />
	<column name="document_srl" type="number" size="11" notnull="notnull" />
	<column name="site_url" type="varchar" size="255" index="idx_site_url" notnull="notnull" />
	<column name="site_data" type="bigtext" notnull="notnull" />
	<column name="update_time" type="bignumber" notnull="notnull" />
	<column name="sns_type" type="varchar" size="20" index="idx_sns_type" />
	<column name="embed_type" type="varchar" size="20" index="idx_embed_type" />
</table>
```
디비 임베이드는 이정도로 깔끔하게 구조화가 가능할듯

해당 임베이드타입과 sns 타입에 따라 데이터 결과값이 달라지는 경우가 있어서 부득이하게 sns타입등등을 같이 추가해야함.

속도 향상.

parserlink.view.php 파일에서 실행되는 동안  return array에 데이터를 담는과정이 있지만 이 과정을 생략하고 바로 디비에서 찾아서 해당 디비를 php가 읽을 수 있는 데이터로 만든다음 쏘기 때문에 속도 향상 엉청 기대.

또 같은 사이트 여러번 파싱하지 않아도됨.

**Comment by bjrambo** [comment]
Add to 94de9c3bfd1cbd3d455c77af4fa6464db7d7d3c8
1차 커밋 완료
해당 커밋에서는 아직 시간설정에 따른 디비 재생성 기능을 포함하고 있지 않음.

**Comment by wookho** [comment]
방금 위 커밋 적용했는데요. 차이가 뭐에요? 이미지와 내용을 저희 사이트 db에 저장하고 거기서 불러오나요?

**Comment by wookho** [comment]
오... 파싱해서 db에 저장한 후 그 이후에는 db에서 정보를 바로 가지고 와서 빠른거군요. 네이버꺼 파싱한번 한 후 다시 페이지뷰 해보니 속도차이가 굉장히 나네요. 좋습니다!

**Comment by wookho** [comment]
특이사항이 있는게 db에서 어떤 것은 수정,삭제가 가능하고 어떤 데이터는 수정,삭제가 안되는걸로 나오네요..

**Comment by bjrambo** [comment]
@wookho 아직 더 테스트 해봐야 해요..ㅋㅋ

**Comment by socialskyo** [comment]
오잉?? 속도가 왜이리 빨라졌어요?? 대단... 기존 애드온 보다 느려서 솔직히 기다려야겠다는 입장이었는데... bb!!

**Comment by bjrambo** [comment]
@socialskyo 앞으로 이것보다 훨신 더 빨라질겁니다.

**Comment by socialskyo** [comment]
@bjrambo 대단해요!!
