### ISSUE TITLE
댓글에도 사용가능하도록 할시에 두 줄이상 띄어쓰기가 안되는 문제

### ISSUE THREAD

**Issue by clamp2x** [bjrambo/parserlink#12]
댓글을 작성시 링크 파싱하기 위해 p태그로 마지막에 감싸는데 그러는 과정에서 댓글에 띄어쓰기를 두줄 이상 하는 경우 한줄로만 인식을 합니다. 
br태그가 먹히지 않고 띄어쓰기 한 공간은 단순히 p태그로만 감싸고 있습니다.

**Comment by bjrambo** [comment]
정확하게 어떤내용을 사용하셧는지.. 해당 부분 소스좀 알려주시면 확인해볼께요..

**Comment by clamp2x** [comment]
모듈의 문제인 줄 알았으나 휴리파파님의 APLOS 보드 스킨에서 일어나는 문제점이었습니다.

https://www.xetown.com/qna/728029

이 모듈의 문제와는 무관하니 이 이슈는 닫도록 하겠습니다. ^^;;
