### ISSUE TITLE
XE임베드파싱 모듈에서 프리뷰가 두 번 출력될 때

### ISSUE THREAD

**Issue by cydemo** [bjrambo/parserlink#17]
div 안에 p가 있고, 그 안에 링크 텍스트가 있어서 파싱이 두 번 일어나는 경우가 있습니다.

근본적인 해결책은 아니지만,
/modules/parserlink/tpl/js/ap_parser.js
20행
var ps = x.find('div, p').filter(function () {
를
var ps = x.find('div:not(:has(p)), p').filter(function () {
로 바꿔주면 일단 해당 문제를 회피할 수 있더군요.

**Comment by wookho** [comment]
저희도 각주를 사용하니 div가 사용되서 2번 출력이 되는 경우가 생겨 이 문제는 처리 되었으면 좋겠네요.

**Comment by bjrambo** [comment]
Fixed eb9a4304156b39a016d685da73b59b8a90ea848f
