### ISSUE TITLE
업데이트 이후 인스타그램 한글 태그의 경우 게시글 못불러옵니다.

### ISSUE THREAD

**Issue by wookho** [bjrambo/parserlink#18]
https://www.instagram.com/explore/tags/태연/

**Comment by wookho** [comment]
최초 문제 발견시 제가 확인했던 내용의 댓글입니다.


신고 공감 수정 삭제  댓글
profile
윤삼	2017.09.03 21:22:01
혹시
$tag = urldecode(urlencode(Context::get('tag')));
도 해보셨나요?
직접 작업하면서 확인을 할 수가 없으니 답답하네요;;
(람보님은 지금쯤 야시장에 계실까...)
신고 공감  댓글
profile
웹지기	2017.09.03 21:27:19
그렇게 하면 다시 /태연/ 요것만 안됩니다 ㅋ
뭐 급한건 아니니 적용할 만한 것 알게 될때 하나씩 해보면 되죠 머....
신고 공감 수정 삭제  댓글
profile
웹지기	2017.09.04 11:41:39
방금 해결했습니다!
$tag = urldecode(Context::get('tag'));
$tag = urlencode($tag);

디코드를 먼저해서 처리 된 것을 문제 없게 만든 후 엔코드 하니 두개 유형의 url 모두 잘 되네요!
신고 공감 수정 삭제  댓글
profile
윤삼	2017.09.04 11:53:48
반대였군요ㅠㅠ
$tag = urldecode(urlencode(Context::get('tag'))); ㅋㅋㅋㅋ

**Comment by bjrambo** [comment]
Fixed https://github.com/bjrambo/parserlink/commit/fb4d615ad62e4679af42ede5f0938c44db422889
