### ISSUE TITLE
MariaDB 사용 시의 파싱모듈의 이상함?

### ISSUE THREAD

**Issue by ghost** [bjrambo/parserlink#27]
안녕하세요. 람보님의 자료들 항상 잘 사용하고 있습니다. ㅎ

파싱 모듈을 사용하려고 하는데 모듈이 정상적으로 작동하지 않아 원인을 찾아보니
(증상 : 로그인을 한 회원이 글을 읽어야 파싱이 이루어지고 파싱 속도도 더딥니다.)

MariaDB를 사용하는 환경에서는 파싱 모듈이 정상적으로 작동하지 않는 것 같다는

이야기를 들었습니다. 

https://xetown.com/qna/906603

어떤 분은 비회원에게만 작동하는 애드온의 문제일 수 있다고 하였는데 의심 가는

애드온들을 꺼도 해결이 되지 않았고 콘솔 창을 살펴봐도 오류 내역은 없습니다.

애초에 애드온도 몇개 사용하지 않구요. ㅜ

그런데 DB 때문에 특정 모듈이 작동하지 않을 수도 있는 것 인지...

만일, DB 때문이 아니라면 이 이슈는 닫아주세요. ㅜㅜ

**Comment by bjrambo** [comment]
@jm3226 제가 첫 Parserlink 모듈을 개발했던 환경은 마리아디비 그당시 최신버전이였습니다.. 따라서 마리아 디비가 문제라고 보여지지 않을 것 같군요..

develop 브랜치에 있는 내용을 다운로드 하셔서 설치 다시 한번 해보시고 증상 알려주시면 감사하겠습니다.

**Comment by ghost** [comment]
최신 develop으로 해봐도 결과는 동일 합니다. ㅜㅜ 이 이슈는 닫겠습니다. 

항상 감사합니다. ㅎㅎ
