### ISSUE TITLE
상단 서버에 요청중 가리기 기능이 누락

### ISSUE THREAD

**Issue by wookho** [bjrambo/parserlink#3]
ajax로드 방식을 바꿔서인지, 파싱 중 페이지 상단에 픽스된 .wfsr인가요 '서버에 요청 중입니다. 잠시만 기다려주십시오' 메시지가 나타납니다. 원래 애드온에선 이 부분이 hide() 처리됐었습니다.

**Comment by bjrambo** [comment]
#4 파싱 후 null 값이 들어오거나 실패했을 경우 출력하지 않도록 되어 있었는데, 이 부분도 반영되지 않은 것 같습니다. 로딩 이미지가 계속 뜨네요;; 가령 http://news.chosun.com/site/data/html_dir/2017/08/28/2017082801773.html 같은 주소로 파싱을 해보면 그렇게 됩니다.

**Comment by bjrambo** [comment]
기록용 : 출력을 디스플레이액션으로 echo로해당코드들을 정리해서 노출시켜야할듯. 액션이 실행되지만 정작 받아들이는값이 전달을 받지못하는 문제로 보여짐.

간단하게 메서드만 호출하면될듯.
