### ISSUE TITLE
실패했을 경우 출력하지 않도록 하는 부분 누락

### ISSUE THREAD

**Issue by wookho** [bjrambo/parserlink#4]
파싱 후 null 값이 들어오거나 실패했을 경우 출력하지 않도록 되어 있었는데, 이 부분도 반영되지 않은 것 같습니다. 로딩 이미지가 계속 뜨네요;; 가령 http://news.chosun.com/site/data/html_dir/2017/08/28/2017082801773.html 같은 주소로 파싱을 해보면 그렇게 됩니다.

**Comment by bjrambo** [comment]
이부분은 ajax방식으로 동작을 해야하는데 XE에서 ajax방식으로 가져오는 방법이 재대로 동작하지 않고 있어서 보류중이에요. 되돌아갈 수 있는 방법을 찾게 된다면 적용할 수 있도록 하겠습니다.

**Comment by bjrambo** [comment]
기록용 : 출력을 디스플레이액션으로 echo로해당코드들을 정리해서 노출시켜야할듯.  액션이 실행되지만 정작 받아들이는값이 전달을 받지못하는 문제로 보여짐.

간단하게 메서드만 호출하면될듯.
