### ISSUE TITLE
설정부분이 동작하지 않습니다.

### ISSUE THREAD

**Issue by wookho** [bjrambo/parserlink#5]
- 일단 설정 페이지 상단에 'Template not found: modules/parserlink/tplheader.html'이 뜹니다.
- '링크 추출 범위'가 적용되지 않습니다. 어떤 옵션은 선택해도 '본문+댓글에서' 모두 파싱이 시도됩니다.
- '로딩 이미지 출력' 옵션 > '출력하지 않음'이 적용되지 않습니다.
- '도메인 출력' > '출력하지 않음'이 적용되지 않습니다.
- '링크 텍스트' > '삭제' 옵션이 적용되지 않습니다. '삭제'를 선택하면 파싱이 성공한 경우 본문에 있는 링크 텍스트를 지울 수 있는 옵션인데 적용되지 않고 있습니다.
- '페이스북 임베드', '트위터 임베드', '인스타그램 임베드', '유튜브 임베드' 옵션들도 적용되지 않습니다. 임베드하지 않고 '일반 출력'을 선택해도 그냥 임베드되고 있습니다.

**Comment by bjrambo** [comment]
* [x] 링크추출 방식에서 values 값이 변경이 되어서 문제 생김 (doc, com, all 이값을 설정과 통일.
* [x] 로딩이미지 #3 and 바로 위 이슈와 함께 value 값확인
* [x] 도메인출력 역시 마찬가지
* [x] 링크텍스트 
* [x] 각 SNS 임베드설정.
