### ISSUE TITLE
상단 메시지 서버에 요청중입니다. 가리기 기능이 인스타 게시글 조회때 반영이 되었으면 합니다.

### ISSUE THREAD

**Issue by wookho** [bjrambo/parserlink#8]
웹사이트,embed 등 에서 상단 메시지 가리는 것이 잘 처리 되었는데요.
XE사이트에서 인스타그램 게시글 불러올때 한번 더 서버에 요청중이 발생하는데 이것은 가려지지 않은 듯 합니다.

이것도 가려줬으면 좋겠네요.

**Comment by wookho** [comment]
https://github.com/bjrambo/parserlink/issues/3

여기서 처리해 주셨던 것 같습니다.

**Comment by bjrambo** [comment]
Fixed in https://github.com/bjrambo/parserlink/commit/d987a260c1e09a419618912dafeeba8c3a517ffa
